[[redirects]]
  from = "/login"
  to = "https://main--velvety-snickerdoodle-4357ab.netlify.app/login"

[[redirects]]
  from = "/user"
  to = "https://main--velvety-snickerdoodle-4357ab.netlify.app/user"